### ISSUE TITLE
metric_logger buggy when doing multi-node training

### ISSUE THREAD

**Issue by hanseungwook** [instructlab/training#133]
In 
https://github.com/instructlab/training/blob/2b744affa58e3e429a4115f73b16a53c4e782226/src/instructlab/training/main_ds.py#L408 ,

each local rank 0 logs to file and this results in json decoding error where multiple objects are concatenated together.

Simple fix would be changing this line to

`if args.global_rank == 0:`

**Comment by aldopareja** [comment]
@RobotSail @Maxusmusti or @JamesKunstle . Can anyone look into this, we should make the log name to have the global rank in the name to avoid this issue.
