### ISSUE TITLE
Update Data Processing and Sampling Selection

### ISSUE THREAD

**Issue by Maxusmusti** [instructlab/training#136]
Data Processing must support pretraining with padded special tokens

Sampler auto-select must work with these pretrain samples (supposedly isn't right now)

**Comment by bbrowning** [comment]
Does #137 fully resolve this issue, or is there another follow-up PR needed to take care of getting the sampler auto-select to work with the pretrain samples?

**Comment by Maxusmusti** [comment]
@bbrowning this is fully resolved, the issue IBMers were running into turned out to be due to them experimenting on an older branch that was made before auto-selection. Thanks for checking! I had forgot to close this issue
