### ISSUE TITLE
Include proper checkpoint saving for LoRA/QLoRA

### ISSUE THREAD

**Issue by Maxusmusti** [instructlab/training#141]
We are currently dumping the full, unmerged state dict when saving model checkpoints. This makes LoRA/QLoRA trained models difficult to load for other components + serving, and default behavior is causing LoRA weights to be dropped. We need to merge the LoRA weights before saving checkpoints, and also potentially dequantize the base model on CPU to do so for QLoRA.

**Comment by nathan-weinberg** [comment]
Fixed by #142
