### ISSUE TITLE
[FSDP] [EPIC] Determine how well FSDP works on Intel Gaudi and AMD MI

### ISSUE THREAD

**Issue by RobotSail** [instructlab/training#202]
We want to verify that FSDP works in the following scenarios:

- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208

**Comment by JamesKunstle** [comment]
We have validated that FSDP works fine on AMD cards. Haven't gotten anything to run correctly on Gaudi cards.
