### ISSUE TITLE
AMD MI Multi-GPU, single-node training

### ISSUE THREAD

**Issue by RobotSail** [instructlab/training#204]

**Comment by JamesKunstle** [comment]
Experimented with different parameters for multi-phase training on these cards. With an `effective_batch_size=128` for the first phase, and `effective_batch_size=3840` for the second phase, MI300x cards with 192GB of VRAM don't sweat under these batch dimensions. For the larger `ebs=3840` I saw a `packing_max_batch_len=~135000`, signaling that that's the upper-limit of tokens that we can fit given the ebs.

However, if we unbound ebs (ebs=1000000) then we can set a `max_batch_len` that fully utilizes the card's vram.

These numbers are data-dependent but should be naively scaled back sufficiently to fit for most datasets:

```
# 8xMI300x
## training
max_batch_len=220000
nproc_per_node=8
## eval
gpus=1

# 4xMI300x
## training
max_batch_len=210000
nproc_per_node=4
## eval
gpus=1

# 2xMI300x, 1xMI300x
## training
max_batch_len=200000
nproc_per_node=2
## eval
gpus=1 
```

**Comment by JamesKunstle** [comment]
NOTE: 240000 for 8xMI300x was confirmed to OOM
