### ISSUE TITLE
Training fails with ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ljmwaugh** [instructlab/training#237]
I received this error on a clean install of v0.18.4 running on an M1 MacBook Pro with 16GB of memory.
I took the defaults when I did `ilab config init`
I successfully generated data with `ilab data generate`

I issued this command to initiate the training
`ilab -v -v model train --gguf-model-path /Users/waughus.ibm.com/Library/Caches/instructlab/models/granite-7b-lab-Q4_K_M.gguf`

I received the message that `Training has started!`

I also saw these messages before the error:
```
Epoch 1: Iter 1: Val loss 4.009, Val took 43.190s
Iter 010: Train loss 3.337, It/sec 0.184, Tokens/sec 76.415
Epoch 1: Iter 10: Val loss 2.406, Val took 43.248s
```
the full error is in the attached file.
I've recreated this error 3-4 times now.
[ilab model train log.txt](https://github.com/user-attachments/files/17209287/ilab.model.train.log.txt)

**Comment by nathan-weinberg** [comment]
Closed by https://github.com/instructlab/instructlab/pull/2369 per @jjasghar
