### ISSUE TITLE
Support for HF Accelerate on Gaudi /AMD cards

### ISSUE THREAD

**Issue by JamesKunstle** [instructlab/training#239]
We chose to use Hugging Face Accelerate to implement support for both DeepSpeed and FSDP. On Nvidia cards, this was a drop-in replacement for a fully custom training loop. However, minor training loop changes may be needed to run on Intel Gaudi and AMD Instinct cards.

One example of this difference is that on Gaudi cards, one switches:

```
- model.to(device_id)
+ model.to(device_hpu)
```

And the Intel Gaudi Pytorch bridge handles moving the model to the correct GPU according to the assigned process rank.

This is different enough from the vanilla Nvidia + torch training loop that Accelerate might not support it directly.

We need to scope:
1. What is the current state of potential support for running distributed training on AMD / Intel
2. Is it possible to non-invasively patch Accelerate to make it work on Intel / AMD
3. How can we propagate those changes to the upstream

Contributing tasks:
- [ ] #240

**Comment by JamesKunstle** [comment]
HF Accelerate works just fine on AMD cards because no code path changes are required. 

On Intel there's evidence to suggest that Gaudi cards need deep changes to Accelerate in order to work correctly. For example, in `optimum-habana` there's an Accelerator implementation that uses the HPU APIs directly: [here](https://github.com/huggingface/optimum-habana/tree/main/optimum/habana)

Pursuing Accelerate on Gaudi- i.e. specifically GaudiAccelerator- is a waste of our time right now because we only intend to use FSDP on Gaudi cards. If we intended to support DeepSpeed for Accelerate we could choose to use GaudiAccelerator as a replacement for the default Accelerator that we're currently using.

**Comment by ktam3** [comment]
Synced with @JamesKunstle - this is something we can't pursue ATM for Gaudi. For AMD, we're already using this codepath - CUDA compatible
