### ISSUE TITLE
Update training config in CLI to reflect new options (8B support)

### ISSUE THREAD

**Issue by ktam3** [instructlab/training#287]
Goal:

Provide high-level goal statement; providing user context and expected user outcome(s) for this Epic. 2-3 sentences... 

Update training config in CLI to reflect new options
 

Acceptance Criteria:

The Acceptance Criteria provides a definition of scope and the expected outcomes - from a users point of view - defines the value proposition

- Update description of is_padding_free flag 
- used_dolomite flag is introduced
- Both need to be properly connected to training library and appropriately described in functionality.

**Comment by junzzhu** [comment]
I wonder if the latest granite-3.0 is within the consideration, as there is a new model - https://huggingface.co/ibm-granite/granite-3.0-8b-base, which has different architecture/model_type from the previous granite-8b.

**Comment by ktam3** [comment]
This is related to the downstream configs Charlie is currently working on
