### ISSUE TITLE
Perf testing between deepspeed and FSDP

### ISSUE THREAD

**Issue by ktam3** [instructlab/training#292]
Ensure performance does not degrade if we switch deepspeed to FSDP for Nvidia support

**Comment by nathan-weinberg** [comment]
Hey @Maxusmusti just as an FYI - I have a PR tee'd up to change the default training backend: https://github.com/instructlab/instructlab/pull/2526

Once the work in this ticket is complete we can merge that in!

**Comment by Maxusmusti** [comment]
I can confirm performance (throughput/memory/time-to-train) is within acceptable bounds to switch to FSDP as default, you can go ahead with #2526
