### ISSUE TITLE
Gaudi: conflicting accelerate requirement with optimum-habana.

### ISSUE THREAD

**Issue by tiran** [instructlab/training#309]
PR #213 added `accelerate>=0.34.2` to instructlab.training. The version requirements conflicts with optimum-habana's version range for `accelerate`. Version 0.13 and latest version [0.14](https://github.com/huggingface/optimum-habana/blob/v1.14.0/setup.py#L35) require "accelerate >= 0.33.0, < 0.34.0`. Would it be possible to change the lower version range for HPU?

Blocks: #294

**Comment by JamesKunstle** [comment]
To solve this we'd have a separate `requirements-hpu.txt` file correct? That'd be fine for builds. We may also _not_ require `accelerate` for Gaudi if `accelerate` doesn't support training on Gaudi cards with the pytorch bridge requirements.

**Comment by JamesKunstle** [comment]
@tiran Opened a PR for this: https://github.com/instructlab/training/pull/320

**Comment by JamesKunstle** [comment]
@tiran I think this is solved. Would you please confirm?

**Comment by tiran** [comment]
@JamesKunstle yes, the problem is solved now. The latest wheel collection does not have a conflict.
