### ISSUE TITLE
Tech Preview compatibility with 8B and FSDP for AMD/ROCm

### ISSUE THREAD

**Issue by ktam3** [instructlab/training#310]
**Acceptance Criteria:**

- Ensure 8B and FSDP TP compatibility with AMD
- Verify and document AMD configuration

**Comment by ktam3** [comment]
@JamesKunstle - PTAL and provide input. Mustafa mentioned you might be doing AMD stuff and to add you to this.

**Comment by JamesKunstle** [comment]
I can own this, sure. Once we have a dev environment w/ our updated 0.19 dependencies for AMD I'll do this.

**Comment by ktam3** [comment]
@Maxusmusti - do you have an update on this?

**Comment by JamesKunstle** [comment]
8B model that we're going to be using became available a day or so ago. Currently waiting on the image for ROCm that'll include the dependencies required for 8B support.

**Comment by ktam3** [comment]
@JamesKunstle - is this now considered complete?

**Comment by JamesKunstle** [comment]
No, we don't have an image yet to verify this.

**Comment by ktam3** [comment]
ack, ty

**Comment by JamesKunstle** [comment]
This has been validated by our perf/scale team
