### ISSUE TITLE
Fix `dolomite_engine` dependency

### ISSUE THREAD

**Issue by russellb** [instructlab/training#33]
`requirements.txt` has `dolomite_engine` in it, but that does not appear to be a valid package installable from pypi.

See comments in https://github.com/instructlab/training/pull/31 hitting this issue.

**Comment by aldopareja** [comment]
it can be installable from pip                                                     `pip install git+https://github.com/ibm-granite/dolomite-engine.git`

**Comment by cdoern** [comment]
for users of the cli even if its accessible via the above pip install, this should be automated or else installing the cli will fail, right?

**Comment by russellb** [comment]
I'll post a fix in a minute ...

**Comment by russellb** [comment]
I pushed a commit to @nathan-weinberg 's branch in #31 that fixes this. I validated it using `tox -e lint` on that branch.

**Comment by Maxusmusti** [comment]
@RobotSail

**Comment by RobotSail** [comment]
Thank you for pushing that fix @russellb. Once that PR merges, we can close this.
