### ISSUE TITLE
Test nvidia / pytorch images from Fabien as they come in

### ISSUE THREAD

**Issue by ktam3** [instructlab/training#87]

**Comment by Maxusmusti** [comment]
Current validated images:
PyTorch development environment: [quay.io/fabiendupont/pytorch-devel:nvidia-24.04-py3-ubi9](http://quay.io/fabiendupont/pytorch-devel:nvidia-24.04-py3-ubi9)
PyTorch runtime (including python-devel): [quay.io/fabiendupont/pytorch-runtime:nvidia-24.04-py3-ubi9](http://quay.io/fabiendupont/pytorch-runtime:nvidia-24.04-py3-ubi9)
